// swift-tools-version: 5.7

// WARNING: Generated by a tool. Do not hand-edit!

import PackageDescription

let package = Package(
    name: "WinAppSDK",
    products: [
        .library(name: "WinAppSDK", type: .dynamic, targets: ["WinAppSDK"]),
    ],
    dependencies: [
        .package(path: "../CWinRT"),
        .package(path: "../UWP"),
        .package(path: "../WindowsFoundation"),
    ],
    targets: [
        .target(
            name: "WinAppSDK",
            dependencies: [
                "CWinRT",
                "UWP",
                "WindowsFoundation",
            ],
            path: "."
        ),
    ]
)
